In [23]:
import numpy as np
import pandas as pd

In [29]:
df=pd.read_csv('hotel_bookings.csv')

In [30]:
df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [27]:
df.describe()

,is_canceled,lead_time,arrival_date_year,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,booking_changes,days_in_waiting_list,adr,required_car_parking_spaces,total_of_special_requests
count,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119386.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000,119390.000000
mean,0.370416,104.011416,2016.156554,27.165173,15.798241,0.927599,2.500302,1.856403,0.103890,0.007949,0.031912,0.087118,0.137097,0.221124,2.321149,101.831122,0.062518,0.571363
std,0.482918,106.863097,0.707476,13.605138,8.780829,0.998613,1.908286,0.579261,0.398561,0.097436,0.175767,0.844336,1.497437,0.652306,17.594721,50.535790,0.245291,0.792798
min,0.000000,0.000000,2015.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-6.380000,0.000000,0.000000
25%,0.000000,18.000000,2016.000000,16.000000,8.000000,0.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,69.290000,0.000000,0.000000
50%,0.000000,69.000000,2016.000000,28.000000,16.000000,1.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,94.575000,0.000000,0.000000
75%,1.000000,160.000000,2017.000000,38.000000,23.000000,2.000000,3.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,126.000000,0.000000,1.000000
max,1.000000,737.000000,2017.000000,53.000000,31.000000,19.000000,50.000000,55.000000,10.000000,10.000000,1.000000,26.000000,72.000000,21.000000,391.000000,5400.000000,8.000000,5.000000

In [17]:
df.shape

(119390, 32)

In [31]:
df.drop(inplace=True,axis=1,labels=['agent','company','hotel','reservation_status_date'])

In [32]:
df.head()

,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,...,reserved_room_type,assigned_room_type,booking_changes,deposit_type,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status
0,0,342,2015,July,27,1,0,0,2,0.0,...,C,C,3,No Deposit,0,Transient,0.0,0,0,Check-Out
1,0,737,2015,July,27,1,0,0,2,0.0,...,C,C,4,No Deposit,0,Transient,0.0,0,0,Check-Out
2,0,7,2015,July,27,1,0,1,1,0.0,...,A,C,0,No Deposit,0,Transient,75.0,0,0,Check-Out
3,0,13,2015,July,27,1,0,1,1,0.0,...,A,A,0,No Deposit,0,Transient,75.0,0,0,Check-Out
4,0,14,2015,July,27,1,0,2,2,0.0,...,A,A,0,No Deposit,0,Transient,98.0,0,1,Check-Out

In [35]:
df.isnull().sum()

is_canceled                         0
lead_time                           0
arrival_date_year                   0
arrival_date_month                  0
arrival_date_week_number            0
arrival_date_day_of_month           0
stays_in_weekend_nights             0
stays_in_week_nights                0
adults                              0
children                            4
babies                              0
meal                                0
country                           488
market_segment                      0
distribution_channel                0
is_repeated_guest                   0
previous_cancellations              0
previous_bookings_not_canceled      0
reserved_room_type                  0
assigned_room_type                  0
booking_changes                     0
deposit_type                        0
days_in_waiting_list                0
customer_type                       0
adr                                 0
required_car_parking_spaces         0
total_of_special_requests           0
reservation_status                  0
dtype: int64

In [52]:
df.fillna(df.mode().iloc[0], inplace=True)

In [69]:
df.isnull().sum()

is_canceled                       0
lead_time                         0
arrival_date_year                 0
arrival_date_month                0
arrival_date_week_number          0
arrival_date_day_of_month         0
stays_in_weekend_nights           0
stays_in_week_nights              0
adults                            0
children                          0
babies                            0
meal                              0
country                           0
market_segment                    0
distribution_channel              0
is_repeated_guest                 0
previous_cancellations            0
previous_bookings_not_canceled    0
reserved_room_type                0
assigned_room_type                0
booking_changes                   0
deposit_type                      0
days_in_waiting_list              0
customer_type                     0
adr                               0
required_car_parking_spaces       0
total_of_special_requests         0
reservation_status                0
dtype: int64

In [77]:
pd.get_option("display.max_columns",None)

20

In [78]:
pd.options.display.max_columns = None

In [79]:
df.head()

,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,children,babies,meal,country,market_segment,distribution_channel,is_repeated_guest,previous_cancellations,previous_bookings_not_canceled,reserved_room_type,assigned_room_type,booking_changes,deposit_type,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status
0,0,342,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,3,No Deposit,0,Transient,0.0,0,0,Check-Out
1,0,737,2015,July,27,1,0,0,2,0.0,0,BB,PRT,Direct,Direct,0,0,0,C,C,4,No Deposit,0,Transient,0.0,0,0,Check-Out
2,0,7,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Direct,Direct,0,0,0,A,C,0,No Deposit,0,Transient,75.0,0,0,Check-Out
3,0,13,2015,July,27,1,0,1,1,0.0,0,BB,GBR,Corporate,Corporate,0,0,0,A,A,0,No Deposit,0,Transient,75.0,0,0,Check-Out
4,0,14,2015,July,27,1,0,2,2,0.0,0,BB,GBR,Online TA,TA/TO,0,0,0,A,A,0,No Deposit,0,Transient,98.0,0,1,Check-Out

In [61]:
from sklearn.preprocessing import OneHotEncoder

In [80]:
df1 = pd.get_dummies(df, columns = ['meal','distribution_channel','reservation_status','country','arrival_date_month','market_segment','deposit_type','customer_type', 'reserved_room_type','assigned_room_type' ])
print(df1)

        is_canceled  lead_time  arrival_date_year  arrival_date_week_number  \
0                 0        342               2015                        27
1                 0        737               2015                        27
2                 0          7               2015                        27
3                 0         13               2015                        27
4                 0         14               2015                        27
...             ...        ...                ...                       ...
119385            0         23               2017                        35
119386            0        102               2017                        35
119387            0         34               2017                        35
119388            0        109               2017                        35
119389            0        205               2017                        35

        arrival_date_day_of_month  stays_in_weekend_nights  \
0                               1                        0
1                               1                        0
2                               1                        0
3                               1                        0
4                               1                        0
...                           ...                      ...
119385                         30                        2
119386                         31                        2
119387                         31                        2
119388                         31                        2
119389                         29                        2

        stays_in_week_nights  adults  children  babies  is_repeated_guest  \
0                          0       2       0.0       0                  0
1                          0       2       0.0       0                  0
2                          1       1       0.0       0                  0
3                          1       1       0.0       0                  0
4                          2       2       0.0       0                  0
...                      ...     ...       ...     ...                ...
119385                     5       2       0.0       0                  0
119386                     5       3       0.0       0                  0
119387                     5       2       0.0       0                  0
119388                     5       2       0.0       0                  0
119389                     7       2       0.0       0                  0

        previous_cancellations  previous_bookings_not_canceled  \
0                            0                               0
1                            0                               0
2                            0                               0
3                            0                               0
4                            0                               0
...                        ...                             ...
119385                       0                               0
119386                       0                               0
119387                       0                               0
119388                       0                               0
119389                       0                               0

        booking_changes  days_in_waiting_list     adr  \
0                     3                     0    0.00
1                     4                     0    0.00
2                     0                     0   75.00
3                     0                     0   75.00
4                     0                     0   98.00
...                 ...                   ...     ...
119385                0                     0   96.14
119386                0                     0  225.43
119387                0                     0  157.71
119388                0                     0  104.40
119389                0                     0  151.20

        required_car_parking_spaces  total_of_special_requests  meal_BB  \
0                                 0                          0        1
1                                 0                          0        1
2                                 0                          0        1
3                                 0                          0        1
4                                 0                          1        1
...                             ...                        ...      ...
119385                            0                          0        1
119386                            0                          2        1
119387                            0                          4        1
119388                            0                          0        1
119389                            0                          2        0

        meal_FB  meal_HB  meal_SC  meal_Undefined  \
0             0        0        0               0
1             0        0        0               0
2             0        0        0               0
3             0        0        0               0
4             0        0        0               0
...         ...      ...      ...             ...
119385        0        0        0               0
119386        0        0        0               0
119387        0        0        0               0
119388        0        0        0               0
119389        0        1        0               0

        distribution_channel_Corporate  distribution_channel_Direct  \
0                                    0                            1
1                                    0                            1
2                                    0                            1
3                                    1                            0
4                                    0                            0
...                                ...                          ...
119385                               0                            0
119386                               0                            0
119387                               0                            0
119388                               0                            0
119389                               0                            0

        distribution_channel_GDS  distribution_channel_TA/TO  \
0                              0                           0
1                              0                           0
2                              0                           0
3                              0                           0
4                              0                           1
...                          ...                         ...
119385                         0                           1
119386                         0                           1
119387                         0                           1
119388                         0                           1
119389                         0                           1

        distribution_channel_Undefined  reservation_status_Canceled  \
0                                    0                            0
1                                    0                            0
2                                    0                            0
3                                    0                            0
4                                    0                            0
...                                ...                          ...
119385                               0                            0
119386                               0                            0
119387                               0                            0
119388                               0                            0
119389                               0                            0

        reservation_status_Check-Out  reservation_status_No-Show  country_ABW  \
0                                  1                           0            0
1                                  1                           0            0
2                                  1                           0            0
3                                  1                           0            0
4                                  1                           0            0
...                              ...                         ...          ...
119385                             1                           0            0
119386                             1                           0            0
119387                             1                           0            0
119388                             1                           0            0
119389                             1                           0            0

        country_AGO  country_AIA  country_ALB  country_AND  country_ARE  \
0                 0            0            0            0            0
1                 0            0            0            0            0
2                 0            0            0            0            0
3                 0            0            0            0            0
4                 0            0            0            0            0
...             ...          ...          ...          ...          ...
119385            0            0            0            0            0
119386            0            0            0            0            0
119387            0            0            0            0            0
119388            0            0            0            0            0
119389            0            0            0            0            0

        country_ARG  country_ARM  country_ASM  country_ATA  country_ATF  \
0                 0            0            0            0            0
1                 0            0            0            0            0
2                 0            0            0            0            0
3                 0            0            0            0            0
4                 0            0            0            0            0
...             ...          ...          ...          ...          ...
119385            0            0            0            0            0
119386            0            0            0            0            0
119387            0            0            0            0            0
119388            0            0            0            0            0
119389            0            0            0            0            0

        country_AUS  country_AUT  country_AZE  country_BDI  country_BEL  \
0                 0            0            0            0            0
1                 0            0            0            0            0
2                 0            0            0            0            0
3                 0            0            0            0            0
4                 0            0            0            0            0
...             ...          ...          ...          ...          ...
119385            0            0            0            0            1
119386            0            0            0            0            0
119387            0            0            0            0            0
119388            0            0            0            0            0
119389            0            0            0            0            0

        country_BEN  country_BFA  country_BGD  country_BGR  country_BHR  \
0                 0            0            0            0            0
1                 0            0            0            0            0
2                 0            0            0            0            0
3                 0            0            0            0            0
4                 0            0            0            0            0
...             ...          ...          ...          ...          ...
119385            0            0            0            0            0
119386            0            0            0            0            0
119387            0            0            0            0            0
119388            0            0            0            0            0
119389            0            0            0            0            0

        country_BHS  country_BIH  country_BLR  country_BOL  country_BRA  \
0                 0            0            0            0            0
1                 0            0            0            0            0
2                 0            0            0            0            0
3                 0            0            0            0            0
4                 0            0            0            0            0
...             ...          ...          ...          ...          ...
119385            0            0            0            0            0
119386            0            0            0            0            0
119387            0            0            0            0            0
119388            0            0            0            0            0
119389            0            0            0            0            0

        country_BRB  country_BWA  country_CAF  country_CHE  country_CHL  \
0                 0            0            0            0            0
1                 0            0            0            0            0
2                 0            0            0            0            0
3                 0            0            0            0            0
4                 0            0            0            0            0
...             ...          ...          ...          ...          ...
119385            0            0            0            0            0
119386            0            0            0            0            0
119387            0            0            0            0            0
119388            0            0            0            0            0
119389            0            0            0            0            0

        country_CHN  country_CIV  country_CMR  country_CN  country_COL  \
0                 0            0            0           0            0
1                 0            0            0           0            0
2                 0            0            0           0            0
3                 0            0            0           0            0
4                 0            0            0           0            0
...             ...          ...          ...         ...          ...
119385            0            0            0           0            0
119386            0            0            0           0            0
119387            0            0            0           0            0
119388            0            0            0           0            0
119389            0            0            0           0            0

        country_COM  country_CPV  country_CRI  country_CUB  country_CYM  \
0                 0            0            0            0            0
1                 0            0            0            0            0
2                 0            0            0            0            0
3                 0            0            0            0            0
4                 0            0            0            0            0
...             ...          ...          ...          ...          ...
119385            0            0            0            0            0
119386            0            0            0            0            0
119387            0            0            0            0            0
119388            0            0            0            0            0
119389            0            0            0            0            0

        country_CYP  country_CZE  country_DEU  country_DJI  country_DMA  \
0                 0            0            0            0            0
1                 0            0            0            0            0
2                 0            0            0            0            0
3                 0            0            0            0            0
4                 0            0            0            0            0
...             ...          ...          ...          ...          ...
119385            0            0            0            0            0
119386            0            0            0            0            0
119387            0            0            1            0            0
119388            0            0            0            0            0
119389            0            0            1            0            0

        country_DNK  country_DOM  country_DZA  country_ECU  country_EGY  \
0                 0            0            0            0            0
1                 0            0            0            0            0
2                 0            0            0            0            0
3                 0            0            0            0            0
4                 0            0            0            0            0
...             ...          ...          ...          ...          ...
119385            0            0            0            0            0
119386            0            0            0            0            0
119387            0            0            0            0            0
119388            0            0            0            0            0
119389            0            0            0            0            0

        country_ESP  country_EST  country_ETH  country_FIN  country_FJI  \
0                 0            0            0            0            0
1                 0            0            0            0            0
2                 0            0            0            0            0
3                 0            0            0            0            0
4                 0            0            0            0            0
...             ...          ...          ...          ...          ...
119385            0            0            0            0            0
119386            0            0            0            0            0
119387            0            0            0            0            0
119388            0            0            0            0            0
119389            0            0            0            0            0

        country_FRA  country_FRO  country_GAB  country_GBR  country_GEO  \
0                 0            0            0            0            0
1                 0            0            0            0            0
2                 0            0            0            1            0
3                 0            0            0            1            0
4                 0            0            0            1            0
...             ...          ...          ...          ...          ...
119385            0            0            0            0            0
119386            1            0            0            0            0
119387            0            0            0            0            0
119388            0            0            0            1            0
119389            0            0            0            0            0

        country_GGY  country_GHA  country_GIB  country_GLP  country_GNB  \
0                 0            0            0            0            0
1                 0            0            0            0            0
2                 0            0            0            0            0
3                 0            0            0            0            0
4                 0            0            0            0            0
...             ...          ...          ...          ...          ...
119385            0            0            0            0            0
119386            0            0            0            0            0
119387            0            0            0            0            0
119388            0            0            0            0            0
119389            0            0            0            0            0


In [82]:
#Split dependent and independent variables
x = df1.iloc[:,1:]
y = df1.iloc[:,0]

In [84]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [87]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
print("X_train ---------->\n", x_train, "\nX_test -------->\n", x_test)

X_train ---------->
 [[-0.35347672 -0.22032994  0.35516212 ... -0.04848472 -0.00323574
  -0.00970762]
 [-0.49422009 -0.22032994  0.64945552 ... -0.04848472 -0.00323574
  -0.00970762]
 [-0.76632396 -0.22032994  0.79660223 ... -0.04848472 -0.00323574
  -0.00970762]
 ...
 [-0.89768444 -1.63344797  0.72302887 ... -0.04848472 -0.00323574
  -0.00970762]
 [ 0.35024017 -1.63344797  0.87017558 ... -0.04848472 -0.00323574
  -0.00970762]
 [ 0.00307317  1.19278808 -0.5277181  ... -0.04848472 -0.00323574
  -0.00970762]]
X_test -------->
 [[ 2.34879614 -0.22032994 -0.60129145 ... -0.04848472 -0.00323574
  -0.00970762]
 [ 0.35962306  1.19278808  0.57588217 ... -0.04848472 -0.00323574
  -0.00970762]
 [ 1.87965155 -1.63344797  0.50230882 ... -0.04848472 -0.00323574
  -0.00970762]
 ...
 [-0.8320042   1.19278808 -1.04273155 ... -0.04848472 -0.00323574
  -0.00970762]
 [-0.93521601 -0.22032994 -0.45414474 ... -0.04848472 -0.00323574
  -0.00970762]
 [-0.41915696  1.19278808 -0.89558485 ... -0.04848472 -0.00323574
  -0.00970762]]

In [89]:
from sklearn.decomposition import PCA
pca = PCA(n_components = 100)
x_train = pca.fit_transform(x_train)
x_test = pca.transform(x_test)
explained_variance = pca.explained_variance_ratio_

In [92]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression(random_state=0,max_iter=1000)
classifier.fit(x_train,y_train)

LogisticRegression(max_iter=1000, random_state=0)

In [96]:
y_pred = classifier.predict(x_test)

In [98]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[14909,    25],
       [   23,  8921]], dtype=int64)

In [100]:
classifier.score(x_test,y_test)

0.9979897813887261